# Data
data_file: '/home/varun/xia_lab/repos/ABUSFusion/scans/20240826/wrist_data.h5'
sequence_length: 2
downsample_factor: 3
val_split: 0.2

# Model
model_save_path: 'experiments/checkpoints/ultrasound_gru_model.pth'

# Training
batch_size: 1
num_epochs: 3
learning_rate: 0.0001
lambda_corr: 0.5
num_workers: 8
log_interval: 10

# Hardware
device: 'cuda'

# Reconstruction
reconstruction_voxel_size: 0.1

# Probe specifications
probe_specs:
  depth: 50  # mm (axial direction)
  width: 38  # mm (lateral direction)
  axial_res: 0.5  # mm
  lateral_res: 2  # mm
  slice_thickness: 5  # mm (elevational direction)
  marker_to_probe_bottom: 54  # mm 